### ISSUE TITLE
why the read_record need &mut self 

### ISSUE THREAD

**Issue by kakalos12** [marirs/rust-ip2location#9]
Hi @marirs , thanks so much for developing this crate. I'm currently intending to integrate it to my application. One thing that I have found is that the read_record function has the definition : 
`    
 fn read_record(&mut self, offset: u32) -> Result<ProxyRecord, Error> {
`
I check that it does not make sense. Because I want to share the DB multiple threads so I try to wrap it in Arc and &mut self doesn't work. I tried to remove the mut and it works. 

Thanks so much

**Comment by marirs** [comment]
Thanks for your update.. I guess it was missed from some previous versions.
Now I've removed it and fixed it too. Published as well.
Thanks
